# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_q <- function(x, y, q) {
    .Call('imputation_dist_q', PACKAGE = 'imputation', x, y, q)
}

dist_q_matrixCpp <- function(x_ref, x_rest, q) {
    .Call('imputation_dist_q_matrixCpp', PACKAGE = 'imputation', x_ref, x_rest, q)
}

